### ISSUE TITLE
meerdere modellen tegelijkertijd naar enabled slepen geeft onderstaande error

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#108]
meerdere modellen tegelijkertijd naar enabled slepen geeft onderstaande error.

```python
2023-09-30T10:52:54     WARNING    Traceback (most recent call last):
              File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\hhnk_threedi_plugin\gui\model_splitter\model_splitter_dialog.py", line 88, in check_consistency_selected_models
              self.check_consistency_models(selected_models + enabled_models)
              File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\hhnk_threedi_plugin\gui\model_splitter\model_splitter_dialog.py", line 92, in check_consistency_models
              models_df = self.modelschematisations.settings_df.loc[models]
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 879, in __getitem__
              return self._getitem_axis(maybe_callable, axis=axis)
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1099, in _getitem_axis
              return self._getitem_iterable(key, axis=axis)
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1037, in _getitem_iterable
              keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
              self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1315, in _validate_read_indexer
              raise KeyError(
             KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index([''], dtype='object', name='name'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

**Comment by wvangerwen** [comment]
had te maken met consistency check verplaatsen van disabled_list naar enabled_list
