### ISSUE TITLE
ValueError als ik "sqlite tests" run

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [threedi/hhnk-threedi-plugin#165]
Onderstaande error krijg ik als ik in het tabje Checks op Sqlite tests klik. De error verschijnt als het proces klaar is (of andersom natuurlijk).

Sqlite die ik gebruik:

[bwn_valkkoog.zip](https://github.com/threedi/hhnk-threedi-plugin/files/14851751/bwn_valkkoog.zip)

```
ValueError: cannot reindex from a duplicate axis
Traceback (most recent call last):
  File "C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\hhnk_threedi_plugin\tasks\sqlite_test_tasks\base_sqlite_test_task.py", line 81, in finished
    raise self.exception
  File "C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\hhnk_threedi_plugin\tasks\sqlite_test_tasks\base_sqlite_test_task.py", line 38, in run
    self.run_custom()
  File "C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\hhnk_threedi_plugin\tasks\sqlite_test_tasks\sqlite_test_tasks.py", line 326, in run_custom
    self.gdf = self.sqlite_test.run_cross_section_no_vertex(database=self.database)
  File "C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\hhnk_threedi_plugin\external-dependencies\hhnk_threedi_tools\core\checks\sqlite\sqlite_main.py", line 520, in run_cross_section_no_vertex
    cross_no_vertex.loc[:, ["distance_to_vertex"]] = nearest_point.apply(get_distance, axis=1)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1642, in _setitem_with_indexer
    value = self._align_series(indexer, value)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexing.py", line 1935, in _align_series
    return ser.reindex(new_ix)._values
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\series.py", line 4399, in reindex
    return super().reindex(index=index, **kwargs)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\generic.py", line 4461, in reindex
    return self._reindex_axes(
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\generic.py", line 4481, in _reindex_axes
    obj = obj._reindex_with_indexers(
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\generic.py", line 4524, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\internals\managers.py", line 1276, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3289, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:
C:/PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python
C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python
C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins
C:/PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\3DIMOD~1.28\apps\grass\grass82\etc\python
C:\Program Files\3DiModellerInterface 3.28\apps\qgis-ltr\resources
C:\PROGRA~1\3DIMOD~1.28\bin\python39.zip
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\DLLs
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib
C:\PROGRA~1\3DIMOD~1.28\bin
C:\Users\lvanwolfswinkel\AppData\Roaming\Python\Python39\site-packages
C:\Users\lvanwolfswinkel\AppData\Roaming\Python\Python39\site-packages\win32
C:\Users\lvanwolfswinkel\AppData\Roaming\Python\Python39\site-packages\win32\lib
C:\Users\lvanwolfswinkel\AppData\Roaming\Python\Python39\site-packages\Pythonwin
C:\PROGRA~1\3DIMOD~1.28\apps\Python39
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\Pythonwin
C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default/python
C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps
C:\Users\lvanwolfswinkel\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\hhnk_threedi_plugin\external-dependencies
.
C:\Program Files\3DiModellerInterface 3.28\apps\qgis-ltr
C:\Program Files\JetBrains\PyCharm 2022.3.2\debug-eggs\pydevd-pycharm.egg
//corp.hhnk.nl/data/Hydrologen_data/Data/personen/sovermeen
```

**Comment by leendertvanwolfswinkel** [comment]
Ik denk dat het probleem met de OSErrors ontstaat zodra er lagen uit de genoemde geopackages aan het QGIS project zijn toegevoegd en je dan de checks opnieuw runt. Die lagen zouden door de tool eerst moeten worden verwijderd
