### ISSUE TITLE
sqlite3 import terminal vs code

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#50]
Sqlite3 werkt niet in de terminal van vscode

```
E:\github\wvangerwen\hhnk-threedi-tools>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1\3DIMOD~1.22\apps\Python39\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\PROGRA~1\3DIMOD~1.22\apps\Python39\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
```

Maar het werkt wel in jupyter binnen vscode
![image](https://user-images.githubusercontent.com/41104904/231982356-0d201e76-3911-4be9-8265-124597207525.png)

Volgens https://stackoverflow.com/questions/54876404/unable-to-import-sqlite3-using-anaconda-python wat aan de paden gedaan. 

Huidige oplossing is handmatige kopie van 
```C:\Program Files\3DiModellerInterface 3.22\bin\sqlite3.dll```
naar
```C:\Program Files\3DiModellerInterface 3.22\apps\Python39\DLLs\sqlite3.dll```
Hiermee werkt het dus wel.

Ofwel dit zo inbakken bij de installatie, of de nieuwe MI 1.28 lost het op, of iets anders...

**Comment by wvangerwen** [comment]
Het probleem is weggaan zonder dat er duidelijk is wat er nu anders is gezet. Niet te reproduceren.
